name: CI
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: "Build (${{ matrix.os }})"
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8"
      - name: Build
        run: |
          cabal install hindent
          cp ~/.cabal/bin/hindent hindent-${{ matrix.os }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: "hindent*"
          include-hidden-files: true
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          pattern: 'binary-*'
          merge-multiple: true
      - name: Check binaries
        run: |
          ls -l hindent-*
          file hindent-*
